/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmenu_job;

import Job.*;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JFrame;
import maplewatch.MapleWatch;
import projectmenu_pickmap.ProjectMenu_PickMap;

/**
 *
 * @author Ham
 */
public class ProjectMenu_Job extends javax.swing.JFrame {

    /**
     * Creates new form ProjectMenu_Job
     */
    static int check = 0;

    public ProjectMenu_Job() {
        initComponents();
        customCursor();

    }
    
    public void customCursor() {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image image_c = toolkit.getImage("maple_cusor.png");
        Cursor c = toolkit.createCustomCursor(image_c, new Point(0,
                0), "img");
        this.setCursor(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Marker", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Character");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -10, 410, 105));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmenu/mapleleaf--1- (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 134, 105));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 600, 400));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmenu_job/archer_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 220, -1, 180));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmenu_job/magician_1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 410, -1, 180));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmenu_job/sword_1.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, 180));

        jButton1.setFont(new java.awt.Font("Segoe Marker", 0, 28)); // NOI18N
        jButton1.setText(">>Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 640, 180, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("      Class description");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 950, 70));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 880, 80));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 890, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmenu_job/Wood.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmenu_job/wooden.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, -40, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmenu/819429-maplestory-wallpaper.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonClick(int check) {
        if (check == 1) {
            jButton5.setBackground(new java.awt.Color(102, 153, 255));
        } else {
            jButton5.setBackground(new java.awt.Color(255, 255, 255));
        }
        if (check == 2) {
            jButton2.setBackground(new java.awt.Color(102, 153, 255));
        } else {
            jButton2.setBackground(new java.awt.Color(255, 255, 255));
        }
        if (check == 3) {
            jButton3.setBackground(new java.awt.Color(102, 153, 255));
        } else {
            jButton3.setBackground(new java.awt.Color(255, 255, 255));
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        check = 2;
        jLabel6.setText("Archers are the range damage class, they have eagle eyes");
        jLabel7.setText("Their Ultimate skill is Spirit Dragon");
        jLabel8.setText("which summon a dragon to attack for them");
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmenu_job/archer_2.png")));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        check = 3;
        jLabel6.setText("Magicians are spell caster,they can wield offensive spells quite effectively");
        jLabel7.setText("Their Ultimate skill is Molten core ");
        jLabel8.setText("which call a meteor, damage enemies in a large area of effect");
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmenu_job/magician_2.png")));

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //first button
        check = 1;
        jLabel6.setText("Swordmans are the melee tank class, they have unmatched Vitality.");
        jLabel7.setText("which mean they can soak up a huge amount of damage. ");
        jLabel8.setText("Their Ultimate skill is Clashing Spiral.");
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmenu_job/sword_2.png")));
    }//GEN-LAST:event_jButton5ActionPerformed
    public int getCheck() {
        return check;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //confirm button
        if (check == 1){
            //sword
            Job j = new Swordman();
            JFrame game = new ProjectMenu_PickMap(j);
            game.setVisible(true);
            this.dispose();

        } else if (check == 2) {
            //archer
            Job j = new Archer();
            JFrame game = new ProjectMenu_PickMap(j);
            game.setVisible(true);
            this.dispose();
        } else if (check == 3) {
            //mage
            Job j = new Magician();
            JFrame game = new ProjectMenu_PickMap(j);
            game.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectMenu_Job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectMenu_Job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectMenu_Job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectMenu_Job.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectMenu_Job().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
